#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Arch with systemd initrd" --class linux --class arch {
	echo "Booting Arch Linux with systemd init"

}

menuentry "Restart" --class restart {
	echo "Rebooting..."
	reboot
}

menuentry "Shut Down" --class shutdown {
	echo "Shutting down..."
	halt
}
